import { spawn, execFile, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs';
import { decodeDoipFrame, type DecodedDoipFrame } from './doip';

const execFileAsync = promisify(execFile);
const CAPTURE_FILTER = 'tcp port 13400 or udp port 13400';
const MAX_EVENTS = 2000;
const MAX_STREAM_BUFFER = 4 * 1024 * 1024;

export type TsharkInterface = {
  id: string;
  label: string;
  raw: string;
};

export type LiveDoipEvent = {
  id: number;
  timestamp: string;
  transport: 'tcp' | 'udp';
  sourceIp?: string;
  destinationIp?: string;
  sourcePort?: number;
  destinationPort?: number;
  decoded: DecodedDoipFrame;
};

export type LiveEcuSummary = {
  logicalAddress: string;
  messageCount: number;
  sentCount: number;
  receivedCount: number;
  ips: string[];
  vin?: string;
  eid?: string;
  gid?: string;
};

type StreamState = {
  nextSequence?: number;
  buffer: Buffer;
  metadata: {
    sourceIp?: string;
    destinationIp?: string;
    sourcePort?: number;
    destinationPort?: number;
    timestamp: string;
  };
};

type CaptureState = {
  running: boolean;
  interfaceId?: string;
  startedAt?: string;
  stoppedAt?: string;
  error?: string;
  stderrTail: string[];
  packetLines: number;
  doipFrames: number;
  process?: ChildProcessWithoutNullStreams;
  events: LiveDoipEvent[];
  streams: Map<string, StreamState>;
  nextEventId: number;
};

const state: CaptureState = {
  running: false,
  stderrTail: [],
  packetLines: 0,
  doipFrames: 0,
  events: [],
  streams: new Map(),
  nextEventId: 1,
};

function possibleTsharkPaths(): string[] {
  const paths = ['tshark'];
  if (process.platform === 'win32') {
    paths.unshift(
      'C:\\Program Files\\Wireshark\\tshark.exe',
      'C:\\Program Files (x86)\\Wireshark\\tshark.exe',
    );
  }
  return paths;
}

async function resolveTshark(): Promise<string> {
  for (const candidate of possibleTsharkPaths()) {
    try {
      if (candidate !== 'tshark' && !fs.existsSync(candidate)) continue;
      await execFileAsync(candidate, ['-v'], { windowsHide: true, timeout: 5000 });
      return candidate;
    } catch {
      // Try next candidate.
    }
  }
  throw new Error('TShark was not found. Install Wireshark with Npcap and ensure tshark.exe is available.');
}

export async function getTsharkReadiness() {
  try {
    const executable = await resolveTshark();
    const { stdout } = await execFileAsync(executable, ['-v'], { windowsHide: true, timeout: 5000 });
    const firstLine = stdout.split(/\r?\n/).find(Boolean) ?? 'TShark detected';
    return {
      installed: true,
      executable,
      version: firstLine,
      captureFilter: CAPTURE_FILTER,
      activeTransmit: false,
      notes: [
        'The live adapter only invokes TShark in capture mode.',
        'The capture filter restricts collection to TCP/UDP port 13400 (DoIP).',
        'No DoIP discovery request, routing activation request, UDS request, or other vehicle transmission is generated by this module.',
      ],
    };
  } catch (error) {
    return {
      installed: false,
      executable: null,
      version: null,
      captureFilter: CAPTURE_FILTER,
      activeTransmit: false,
      error: error instanceof Error ? error.message : 'Unable to detect TShark.',
    };
  }
}

export async function listTsharkInterfaces(): Promise<TsharkInterface[]> {
  const executable = await resolveTshark();
  const { stdout } = await execFileAsync(executable, ['-D'], { windowsHide: true, timeout: 8000 });
  return stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((raw) => {
      const match = raw.match(/^(\d+)\.\s+(.+)$/);
      return {
        id: match?.[1] ?? raw,
        label: match?.[2] ?? raw,
        raw,
      };
    });
}

function parseHexBytes(value: string): Buffer {
  const normalized = value.replace(/:/g, '').replace(/\s+/g, '');
  if (!normalized || normalized.length % 2 !== 0 || !/^[0-9a-f]+$/i.test(normalized)) return Buffer.alloc(0);
  return Buffer.from(normalized, 'hex');
}

function splitCompleteDoipFrames(buffer: Buffer): { frames: Buffer[]; remainder: Buffer } {
  const frames: Buffer[] = [];
  let offset = 0;

  while (offset + 8 <= buffer.length) {
    const version = buffer[offset];
    const inverse = buffer[offset + 1];
    if (((version ^ inverse) & 0xff) !== 0xff) {
      offset += 1;
      continue;
    }

    const payloadLength = buffer.readUInt32BE(offset + 4);
    const frameLength = 8 + payloadLength;
    if (frameLength < 8 || frameLength > 16 * 1024 * 1024) {
      offset += 1;
      continue;
    }
    if (offset + frameLength > buffer.length) break;

    frames.push(buffer.subarray(offset, offset + frameLength));
    offset += frameLength;
  }

  return { frames, remainder: buffer.subarray(offset) };
}

function pushEvent(event: Omit<LiveDoipEvent, 'id'>) {
  state.events.push({ id: state.nextEventId++, ...event });
  state.doipFrames += 1;
  if (state.events.length > MAX_EVENTS) state.events.splice(0, state.events.length - MAX_EVENTS);
}

function decodeAndPush(
  transport: 'tcp' | 'udp',
  timestamp: string,
  sourceIp: string | undefined,
  destinationIp: string | undefined,
  sourcePort: number | undefined,
  destinationPort: number | undefined,
  frameBuffer: Buffer,
) {
  try {
    const decoded = decodeDoipFrame(frameBuffer.toString('hex'));
    pushEvent({ transport, timestamp, sourceIp, destinationIp, sourcePort, destinationPort, decoded });
  } catch {
    // Ignore malformed/incomplete data from the live stream; capture itself continues.
  }
}

function handleUdpPayload(
  timestamp: string,
  sourceIp: string | undefined,
  destinationIp: string | undefined,
  sourcePort: number | undefined,
  destinationPort: number | undefined,
  payload: Buffer,
) {
  let remainder = payload;
  while (remainder.length >= 8) {
    const { frames, remainder: next } = splitCompleteDoipFrames(remainder);
    for (const frame of frames) decodeAndPush('udp', timestamp, sourceIp, destinationIp, sourcePort, destinationPort, frame);
    if (next.length === remainder.length) break;
    remainder = next;
  }
}

function handleTcpPayload(
  timestamp: string,
  sourceIp: string | undefined,
  destinationIp: string | undefined,
  sourcePort: number | undefined,
  destinationPort: number | undefined,
  sequence: number | undefined,
  payload: Buffer,
) {
  if (!payload.length) return;
  const key = `${sourceIp ?? '?'}:${sourcePort ?? 0}>${destinationIp ?? '?'}:${destinationPort ?? 0}`;
  const stream = state.streams.get(key) ?? {
    buffer: Buffer.alloc(0),
    metadata: { sourceIp, destinationIp, sourcePort, destinationPort, timestamp },
  };

  let chunk = payload;
  if (sequence !== undefined && stream.nextSequence !== undefined) {
    if (sequence < stream.nextSequence) {
      const overlap = stream.nextSequence - sequence;
      if (overlap >= chunk.length) return;
      chunk = chunk.subarray(overlap);
    } else if (sequence > stream.nextSequence) {
      // Gap: reset this directional stream rather than incorrectly stitching unrelated bytes.
      stream.buffer = Buffer.alloc(0);
    }
  }

  stream.buffer = Buffer.concat([stream.buffer, chunk]);
  stream.metadata = { sourceIp, destinationIp, sourcePort, destinationPort, timestamp };
  if (sequence !== undefined) stream.nextSequence = sequence + payload.length;

  const { frames, remainder } = splitCompleteDoipFrames(stream.buffer);
  stream.buffer = remainder.length > MAX_STREAM_BUFFER ? remainder.subarray(remainder.length - MAX_STREAM_BUFFER) : remainder;
  state.streams.set(key, stream);

  for (const frame of frames) {
    decodeAndPush('tcp', timestamp, sourceIp, destinationIp, sourcePort, destinationPort, frame);
  }
}

function parsePort(value: string): number | undefined {
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function handleTsharkLine(line: string) {
  if (!line.trim()) return;
  state.packetLines += 1;
  const fields = line.replace(/\r$/, '').split('\t');
  while (fields.length < 10) fields.push('');

  const [epoch, sourceIp, destinationIp, tcpSourcePort, tcpDestinationPort, tcpSequence, tcpPayload, udpSourcePort, udpDestinationPort, udpPayload] = fields;
  const timestamp = Number.isFinite(Number(epoch)) ? new Date(Number(epoch) * 1000).toISOString() : new Date().toISOString();

  const tcpBytes = parseHexBytes(tcpPayload);
  if (tcpBytes.length) {
    handleTcpPayload(
      timestamp,
      sourceIp || undefined,
      destinationIp || undefined,
      parsePort(tcpSourcePort),
      parsePort(tcpDestinationPort),
      parsePort(tcpSequence),
      tcpBytes,
    );
  }

  const udpBytes = parseHexBytes(udpPayload);
  if (udpBytes.length) {
    handleUdpPayload(
      timestamp,
      sourceIp || undefined,
      destinationIp || undefined,
      parsePort(udpSourcePort),
      parsePort(udpDestinationPort),
      udpBytes,
    );
  }
}

function appendStderr(text: string) {
  for (const line of text.split(/\r?\n/).filter(Boolean)) state.stderrTail.push(line);
  if (state.stderrTail.length > 30) state.stderrTail.splice(0, state.stderrTail.length - 30);
}

export async function startPassiveCapture(interfaceId: string) {
  if (state.running) throw new Error('A passive capture is already running.');
  if (!interfaceId.trim()) throw new Error('A TShark capture interface must be selected.');

  const executable = await resolveTshark();
  state.error = undefined;
  state.stderrTail = [];
  state.packetLines = 0;
  state.doipFrames = 0;
  state.events = [];
  state.streams.clear();
  state.nextEventId = 1;
  state.interfaceId = interfaceId.trim();
  state.startedAt = new Date().toISOString();
  state.stoppedAt = undefined;

  const args = [
    '-l', '-n',
    '-i', state.interfaceId,
    '-f', CAPTURE_FILTER,
    '-T', 'fields',
    '-E', 'separator=\t',
    '-E', 'quote=n',
    '-E', 'occurrence=f',
    '-e', 'frame.time_epoch',
    '-e', 'ip.src',
    '-e', 'ip.dst',
    '-e', 'tcp.srcport',
    '-e', 'tcp.dstport',
    '-e', 'tcp.seq',
    '-e', 'tcp.payload',
    '-e', 'udp.srcport',
    '-e', 'udp.dstport',
    '-e', 'udp.payload',
  ];

  const child = spawn(executable, args, { windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  state.process = child;
  state.running = true;

  let stdoutBuffer = '';
  child.stdout.on('data', (chunk: Buffer | string) => {
    stdoutBuffer += chunk.toString();
    const lines = stdoutBuffer.split(/\r?\n/);
    stdoutBuffer = lines.pop() ?? '';
    for (const line of lines) handleTsharkLine(line);
  });
  child.stderr.on('data', (chunk: Buffer | string) => appendStderr(chunk.toString()));
  child.on('error', (error) => {
    state.error = error.message;
    state.running = false;
    state.stoppedAt = new Date().toISOString();
    state.process = undefined;
  });
  child.on('exit', (code, signal) => {
    if (stdoutBuffer.trim()) handleTsharkLine(stdoutBuffer);
    state.running = false;
    state.stoppedAt = new Date().toISOString();
    state.process = undefined;
    if (code && code !== 0 && !state.error) state.error = `TShark exited with code ${code}${signal ? ` (${signal})` : ''}.`;
  });

  return getPassiveCaptureSnapshot();
}

export function stopPassiveCapture() {
  if (state.process && state.running) {
    state.process.kill('SIGTERM');
  }
  state.running = false;
  state.stoppedAt = new Date().toISOString();
  return getPassiveCaptureSnapshot();
}

function buildLiveInventory(): LiveEcuSummary[] {
  const map = new Map<string, LiveEcuSummary>();
  const touch = (address: string, direction: 'sent' | 'received', event: LiveDoipEvent) => {
    const current = map.get(address) ?? { logicalAddress: address, messageCount: 0, sentCount: 0, receivedCount: 0, ips: [] };
    current.messageCount += 1;
    if (direction === 'sent') current.sentCount += 1; else current.receivedCount += 1;
    for (const ip of [event.sourceIp, event.destinationIp]) if (ip && !current.ips.includes(ip)) current.ips.push(ip);
    map.set(address, current);
    return current;
  };

  for (const event of state.events) {
    const announcement = event.decoded.vehicleAnnouncement;
    if (announcement) {
      const current = touch(announcement.logicalAddress, 'sent', event);
      current.vin = announcement.vin || current.vin;
      current.eid = announcement.eid;
      current.gid = announcement.gid;
    }
    const diagnostic = event.decoded.diagnosticMessage;
    if (diagnostic) {
      touch(diagnostic.sourceAddress, 'sent', event);
      touch(diagnostic.targetAddress, 'received', event);
    }
  }

  return [...map.values()].sort((a, b) => a.logicalAddress.localeCompare(b.logicalAddress));
}

export function getPassiveCaptureSnapshot(afterEventId = 0) {
  const events = state.events.filter((event) => event.id > afterEventId);
  return {
    running: state.running,
    interfaceId: state.interfaceId ?? null,
    startedAt: state.startedAt ?? null,
    stoppedAt: state.stoppedAt ?? null,
    error: state.error ?? null,
    stderrTail: state.stderrTail,
    captureFilter: CAPTURE_FILTER,
    packetLines: state.packetLines,
    doipFrames: state.doipFrames,
    totalBufferedEvents: state.events.length,
    latestEventId: state.events.at(-1)?.id ?? 0,
    events,
    ecuInventory: buildLiveInventory(),
    transmitEnabled: false,
  };
}
